name: recall

networks:
  dev:

include:
  - ./backend/compose.yaml
  - ./frontend/compose.yaml

services:
  nginx:
    container_name: recall-nginx
    image: nginx:1.27.3-alpine
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - $CERTBOT_PATH/www/:/var/www/certbot/:ro
      - $CERTBOT_PATH/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - dev
  certbot:
    image: certbot/certbot:latest
    volumes:
      - $CERTBOT_PATH/www/:/var/www/certbot/:rw
      - $CERTBOT_PATH/conf/:/etc/letsencrypt/:rw
    networks:
      - dev